# Use a imagem base do Node.js
FROM node:20

# Definir diretório de trabalho
WORKDIR /usr/src/app

# Copiar arquivos de configuração do npm
COPY package*.json ./

# Instalar dependências do npm
RUN npm install

# Copiar o restante dos arquivos da aplicação
COPY . .

# Comando para iniciar a aplicação
CMD ["npm", "start"]