services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: container_app
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
    volumes:
      - .:/usr/src/app
    command: npm run dev

  postgres:
    image: postgres:16-alpine
    container_name: container_postgres
    restart: always
    environment:
      POSTGRES_USER: userdb
      POSTGRES_PASSWORD: passworddb
      POSTGRES_DB: meetsyncdb
    ports:
      - "5432:5432"
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: container_pgadmin
    platform: linux/x86_64
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin